server:
  port: 8077

logging.level.org.springframework.web: DEBUG

eureka:
  client:
    enabled: true
    serviceUrl.defaultZone: http://localhost:8075/eureka
    
# For actuator http://localhost:8077/actuator
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: details,info    

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ugt1
    password: Welcome@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
